# App
spring.application.name=flowdesk
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/flowdesk_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Mexico_City
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true